#!/bin/bash
# configure-pvm-use.sh — Auto-configure pvm-use skill for all agents after deployment
#
# Run this as the final step of PVM backend deployment.
# It discovers the API Gateway URL and writes config to all agent workspaces.
#
# Usage:
#   bash scripts/configure-pvm-use.sh [--api-id API_ID] [--region REGION] [--stage STAGE]
#
# If --api-id is omitted, auto-discovers from API Gateway by name "pvm-api".
#
set -euo pipefail

REGION="${AWS_DEFAULT_REGION:-us-west-2}"
STAGE="prod"
API_ID=""
OPENCLAW_HOME="${OPENCLAW_HOME:-$HOME/.openclaw}"

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --api-id)  API_ID="$2"; shift 2 ;;
    --region)  REGION="$2"; shift 2 ;;
    --stage)   STAGE="$2"; shift 2 ;;
    --openclaw-home) OPENCLAW_HOME="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: configure-pvm-use.sh [--api-id ID] [--region REGION] [--stage STAGE]"
      echo ""
      echo "Auto-configures pvm-use skill for all OpenClaw agents."
      echo "If --api-id is omitted, discovers the PVM API Gateway automatically."
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# Auto-discover API Gateway ID if not provided
if [[ -z "$API_ID" ]]; then
  echo "🔍 Discovering PVM API Gateway..."
  API_ID=$(aws apigateway get-rest-apis --region "$REGION" \
    --query "items[?name=='pvm-api'].id | [0]" --output text 2>/dev/null || true)

  if [[ -z "$API_ID" || "$API_ID" == "None" ]]; then
    echo "❌ Could not find API Gateway named 'pvm-api' in $REGION"
    echo "   Use --api-id to specify manually"
    exit 1
  fi
  echo "   Found: $API_ID"
fi

API_BASE="https://${API_ID}.execute-api.${REGION}.amazonaws.com/${STAGE}"

echo "📡 API Base URL: $API_BASE"
echo ""

# Verify the API is responding
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$API_BASE/permissions/status/test" 2>/dev/null || echo "000")
if [[ "$HTTP_CODE" == "000" ]]; then
  echo "⚠️  Warning: Could not reach API at $API_BASE (may not be deployed yet)"
else
  echo "✅ API reachable (HTTP $HTTP_CODE)"
fi

# Find all agent workspaces and configure pvm-use
CONFIGURED=0
SKIPPED=0

for ws in "$OPENCLAW_HOME"/workspace-*; do
  [[ -d "$ws" ]] || continue
  agent=$(basename "$ws" | sed 's/workspace-//')

  # Check if pvm-use skill is installed
  if [[ ! -d "$ws/skills/pvm-use" ]]; then
    echo "   ⏭️  $agent — pvm-use skill not installed, skipping"
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  # Write config
  mkdir -p "$ws/skills/pvm-use/config"
  cat > "$ws/skills/pvm-use/config/pvm.env" << EOF
# PVM Configuration — auto-generated by pvm-deploy
# $(date -u +"%Y-%m-%dT%H:%M:%SZ")
PVM_API_BASE="$API_BASE"
PVM_REGION="$REGION"
EOF

  echo "   ✅ $agent — configured"
  CONFIGURED=$((CONFIGURED + 1))
done

echo ""
echo "Done! Configured $CONFIGURED agent(s), skipped $SKIPPED."

if [[ $CONFIGURED -eq 0 ]]; then
  echo ""
  echo "No agents have pvm-use installed. Deploy it first:"
  echo "  cp -r skills/pvm-use /path/to/workspace-AGENT/skills/"
fi
